### ISSUE TITLE
Crashlooping otv-backend pods on community cluster

### ISSUE THREAD

**Issue by Nexus2k** [w3f/1k-validators-be#1512]
I see crashlooping otv-backend pods on the community cluster. The last error that gets logged is the following:
```
2021-12-30T13:48:30.908Z info: (Db::setClaimDelta) Setting claim delta timestamp: NaN, blocks: NaN
/code/node_modules/mongoose/lib/query.js:4594
  const castError = new CastError();
                    ^

CastError: Cast to Number failed for value "NaN" (type number) at path "avgClaimTimestampDelta"
    at model.Query.exec (/code/node_modules/mongoose/lib/query.js:4594:21)
    at Db.<anonymous> (/code/build/db/index.js:627:18)
    at Generator.next (<anonymous>)
    at /code/build/db/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/code/build/db/index.js:4:12)
    at Db.setClaimDelta (/code/build/db/index.js:618:16)
    at /code/build/jobs.js:314:18
    at Generator.next (<anonymous>)
    at fulfilled (/code/build/jobs.js:5:58) {
  messageFormat: undefined,
  stringValue: '"NaN"',
  kind: 'Number',
  value: NaN,
  path: 'avgClaimTimestampDelta',
  reason: AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
  
    assert.ok(!isNaN(val))
  
      at castNumber (/code/node_modules/mongoose/lib/cast/number.js:28:10)
      at SchemaNumber.cast (/code/node_modules/mongoose/lib/schema/number.js:378:12)
      at SchemaNumber.SchemaType.applySetters (/code/node_modules/mongoose/lib/schematype.js:1135:12)
      at SchemaNumber.SchemaType._castForQuery (/code/node_modules/mongoose/lib/schematype.js:1567:15)
      at SchemaNumber.castForQuery (/code/node_modules/mongoose/lib/schema/number.js:432:14)
      at SchemaNumber.SchemaType.castForQueryWrapper (/code/node_modules/mongoose/lib/schematype.js:1534:20)
      at castUpdateVal (/code/node_modules/mongoose/lib/helpers/query/castUpdate.js:523:19)
      at walkUpdatePath (/code/node_modules/mongoose/lib/helpers/query/castUpdate.js:343:24)
      at castUpdate (/code/node_modules/mongoose/lib/helpers/query/castUpdate.js:95:7)
      at model.Query._castUpdate (/code/node_modules/mongoose/lib/query.js:4803:10) {
    generatedMessage: true,
    code: 'ERR_ASSERTION',
    actual: false,
    expected: true,
    operator: '=='
  },
  valueType: 'number'
}
```

I assume we need to add some code to prevent writing NaN values.

**Comment by Nexus2k** [comment]
The fix helped however we now see crashes due API rate limiting of subscan. Will mentioned he has an API key for it and that we can for now uncomment the subscan job.
